### ISSUE TITLE
Screenshots of UI launcher are too cropped

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-docs#26]
The explanation of how to use the launcher (introduced to fix #18) repeatedly says 'press `Next` to proceed', but the `Next` button has been cropped out of the accompanying screenshots.

**Comment by senakafdo** [comment]
I don't see a reason as to why this needs to be fixed, @jamesscottbrown, as anyone using the UI would easily notice the `Next` button. The purpose of these images were to give the user some idea of what needs to be filled, which is why the focus is the form and not the entire screen. I would rather put more effort on issues that are a bit more meaningful.

Anyway, if you are interested in fixing this, please create a PR.

**Comment by jamesscottbrown** [comment]
The appearance of the form could be improved by removing the `min-height: 450px` property definition for `.step`.

**Comment by senakafdo** [comment]
For the record, the `min-height: 450px` setting is required to ensure all steps of the form render properly and also preserve similar dimensions. Therefore, I have changed this to `325px` simply for the benefit of taking screenshots for the docs, and have not changed it thereafter.
